### ISSUE TITLE
Inquiry regarding the YAML file of Docker Compose

### ISSUE THREAD

**Issue by Jenhaoo** [yrzr/gitlab-ce-arm64v8-docker#5]
According to the official manual of GitLab, GitLab supports running with Compose. The official example provided for creation is as follows.

```yaml
version: '3.6'
services:
  gitlab:
    image: gitlab/gitlab-ee:<version>-ee.0
    container_name: gitlab
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
    ports:
      - '8929:8929'
      - '443:443'
      - '2424:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'
```
My question is, does the environment support configuration through `GITLAB_OMNIBUS_CONFIG`, and does this repository also support these parameters? Or is it necessary to run it first and then enter the environment for configuration?
